### ISSUE TITLE
Help need to move from karma-jasmine-jquery to this

### ISSUE THREAD

**Issue by chauhankiran** [AStoker/karma-jasmine-jquery#1]
I've one project in which we're using `karma-jasmine-jquery` and due to git:// protocol, it continually fails in deployment. While looking over the issue and PR I found this repo. I'm planning to use this instead of the current one. In such a case, can anybody help me with the following?

1. If I use this repo `karma-jasmine-jquery-2`, do I need to change anything in the code?
2. If I try to uninstall the `karma-jasmine-query` via `npm uninstall`, it hangs. How can I properly uninstall and then install this repo? Or is there other steps I can follow to include this?

**Comment by AStoker** [comment]
Sorry, I haven't maintained this project as we've been moving to jest and away from jquery. Hope you were able to solve what you needed @chauhankiran !
